name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1,3,5,7
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "enigmatic-citadel-01269" #Must be unique in Heroku
          heroku_email: "prakashsellathurai@gmail.com"
